---
name: 'Trigger pull artifacts'
author: 'icogn'
description: 'Action to trigger the centralized pull-artifacts workflow'

branding:
  icon: 'plus'
  color: 'gray-dark'

inputs:
  token:
    description: Repository access token
    required: true

  privateKey:
    description: RSA-SHA256 private key
    required: true

  passphrase:
    description: Passphrase which goes with the privateKey
    required: false

  artifactInfo:
    description: Artifact info
    required: true

runs:
  using: node20
  main: action-dist/index.js
