---
name: 'Pull web artifacts'
author: 'icogn'
description: 'Action to verify and add web artifacts to branch for use by offline generator'

branding:
  icon: 'plus'
  color: 'gray-dark'

inputs:
  github-token:
    description: Repository access token
    required: true

  clientPayload:
    description: Client payload
    required: true

# outputs:
#   value:
#     description: The version

runs:
  using: node20
  main: action-dist/index.js
