---
name: 'Pull web artifacts'
author: 'icogn'
description: 'Action to verify and add web artifacts to branch for use by offline generator'

branding:
  icon: 'plus'
  color: 'gray-dark'

inputs:
  github-token:
    description: Repository access token
    required: true

  clientPayload:
    description: Client payload. This is required if `clientPayloadFromFile` is not true
    required: false

  clientPayloadFromFile:
    description: Set to 'true' if should read clientPayload from file
    required: false

  owner:
    description: Current repo owner
    required: true

  repo:
    description: Current repo
    required: true

# outputs:
#   value:
#     description: The version

runs:
  using: node20
  main: action-dist/index.js
