name: Website Artifact
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_website:
    # permissions: write-all
    strategy:
      fail-fast: true
      matrix:
        # os: [windows-latest]
        os: [ubuntu-latest]
        # os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    environment: ${{ vars.DEV_BRANCH_NAME }}

    steps:
      - uses: actions/checkout@v4

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20.17.0'
      # - name: Setup yarn
      #   run: npm install -g yarn

      - uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          cache: 'yarn'

      - uses: qoomon/actions--context@v2
        id: context

      - if: ${{ steps.context.outputs.environment == '' }}
        name: Ensure environment defined
        run: exit 1

      # - run: |
      #     echo "Current Environment: ${{ steps.context.outputs.environment }}"
      #     echo "Job Logs: ${{ steps.context.outputs.job_log_url }}"

      - uses: martinbeentjes/npm-get-version-action@v1.3.1
        id: package-version

      - run: echo ${{ steps.package-version.outputs.current-version }}

      - uses: matt-usurp/validate-semver@v2
        id: semver
        with:
          version: ${{ steps.package-version.outputs.current-version }}-${{ steps.context.outputs.environment }}.${{ vars.TESTREPOVAR }}

      - run: |
          echo "v${{ steps.semver.outputs.version }}"
          echo "v${{ steps.semver.outputs.major }}"
          echo "v${{ steps.semver.outputs.minor }}"
          echo "v${{ steps.semver.outputs.patch }}"
          echo "v${{ steps.semver.outputs.prerelease }}"
          echo "v${{ steps.semver.outputs.build }}"

      - run: yarn --immutable

      - run: |
          gh variable list
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - run: echo ${{ vars.TESTREPOVAR }}
      - run: echo ${{ steps.context.outputs.environment }}

      # - uses: action-pack/increment@v2
      - uses: ./scripts/workflows/increment
        id: increment
        with:
          name: 'TESTREPOVAR'
          token: ${{ secrets.GH_PAT }}
          environment: ${{ steps.context.outputs.environment }}

      # - uses: ./scripts/ci/set-github-variable.js
      #   with:
      #     name: 'SAMPLE_VAR'
      #     value: 'Hello World'
      #     repository: mmoyaferrer/set-github-variable
      #     token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - run: yarn --cwd website run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: asdf-${{ matrix.os }}
          include-hidden-files: true # so includes .next folder
          path: website/.next/standalone
