name: Website Artifact
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_website:
    strategy:
      fail-fast: true
      matrix:
        # os: [windows-latest]
        os: [ubuntu-latest, windows-latest]
        # os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20.17.0'
      # - name: Setup yarn
      #   run: npm install -g yarn

      - uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          cache: 'yarn'

      - run: yarn --immutable
      - run: yarn --cwd website run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: asdf-${{ matrix.os }}
          path: website/.next/standalone
