# Note that the artifacts which have names that are a long string of random
# characters are for combining the matrix output for each OS
name: Website Artifact
on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'
      # - main

jobs:
  get_environment_name:
    runs-on: ubuntu-latest
    outputs:
      env: '${{ steps.regex-match.outputs.group1 }}'
    steps:
      - run: rustc -vV
      - run: gcc -v

      - run: exit 1

      - uses: kaisugi/action-regex-match@v1.0.1
        name: Get environment name from branch name
        id: regex-match
        with:
          text: ${{ github.ref_name }}
          regex: '^release\/([a-z]+)$'

      - if: ${{ steps.regex-match.outputs.group1 == '' }}
        name: Exit if invalid environment name
        run: exit 1

  increment_validate_version:
    needs: [get_environment_name]
    runs-on: [ubuntu-latest]
    environment: ${{ needs.get_environment_name.outputs.env }}
    outputs:
      env: ${{ needs.get_environment_name.outputs.env }}
    steps:
      - run: echo ${{ github.sha }}
        name: Echo github.sha

      - run: echo ${{ needs.get_environment_name.outputs.env }}

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          cache: 'yarn'

      - run: yarn --immutable

      # Increment the build number ASAP (once we have a valid environment and yarn has run)
      # Important to use `steps.increment.outputs.value` and not vars.BUILD_NUMBER after this.
      # vars.BUILD_NUMBER does not reflect the changed value.
      - uses: ./scripts/workflows/increment
        name: Increment build number
        id: increment
        with:
          name: 'BUILD_NUMBER'
          token: ${{ secrets.GH_PAT }}
          environment: ${{ needs.get_environment_name.outputs.env }}

      # - uses: martinbeentjes/npm-get-version-action@v1.3.1
      #   id: package-version
      #   name: Get root package.json version

      - uses: ./scripts/workflows/package-version
        id: package-version
        name: Get root package.json version

      - uses: kaisugi/action-regex-match@v1.0.1
        name: Check package.json version is valid
        id: regex-match-version
        with:
          text: ${{ steps.package-version.outputs.value }}
          regex: '^\d+\.\d+\.\d+$'

      - if: ${{ steps.regex-match-version.outputs.match == '' }}
        name: Exit if invalid package.json version
        run: exit 1

      - run: echo ${{ steps.package-version.outputs.value }}
        name: Echo root package.json version

  build_website:
    needs: [increment_validate_version]
    environment: ${{ needs.increment_validate_version.outputs.env }}
    outputs:
      env: ${{ needs.increment_validate_version.outputs.env }}
    strategy:
      fail-fast: true
      matrix:
        # os: [ubuntu-latest]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - run: echo ${{ github.sha }}
        name: Echo github.sha

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          cache: 'yarn'

      - run: yarn --immutable

      - uses: ./scripts/workflows/package-version
        id: package-version
        name: Get root package.json version

      - uses: matt-usurp/validate-semver@v2
        id: semver
        with:
          version: ${{ steps.package-version.outputs.value }}-${{ needs.increment_validate_version.outputs.env }}.${{ vars.BUILD_NUMBER }}

      - run: |
          echo "${{ steps.semver.outputs.version }}"
          echo "${{ steps.semver.outputs.major }}"
          echo "${{ steps.semver.outputs.minor }}"
          echo "${{ steps.semver.outputs.patch }}"
          echo "${{ steps.semver.outputs.prerelease }}"
          echo "${{ steps.semver.outputs.build }}"

      # - run: |
      #     gh variable list
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_PAT }}

      # - uses: ./scripts/ci/set-github-variable.js
      #   with:
      #     name: 'SAMPLE_VAR'
      #     value: 'Hello World'
      #     repository: mmoyaferrer/set-github-variable
      #     token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - run: yarn --cwd website run build

      - uses: vimtor/action-zip@v1.2
        with:
          files: website/.next/standalone
          dest: downloadedArtifacts/asdf-${{ matrix.os }}.zip

      - name: Display structure of downloaded files
        run: ls -R downloadedArtifacts

      # - name: Download Artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: asdf-${{ matrix.os }}
      #     path: downloadedArtifacts

      # - uses: 'FKLC/sign-files-action@v1.0.0'
      - uses: ./scripts/workflows/sign-files
        id: sign-files
        with:
          privateKey: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          file: downloadedArtifacts/asdf-${{ matrix.os }}.zip

      - run: echo ${{ steps.sign-files.outputs.value }}

      - name: Display structure of downloaded files
        run: ls -R downloadedArtifacts

      - name: Upload Artifact
        id: upload-web-zip
        uses: actions/upload-artifact@v4
        with:
          name: asdf-${{ matrix.os }}
          # include-hidden-files: true # so includes .next folder
          # path: website/.next/standalone
          path: downloadedArtifacts/asdf-${{ matrix.os }}.zip

      # - name: Upload Artifact
      #   id: upload-web-zip-sig
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: asdf-${{ matrix.os }}.sig
      #     # include-hidden-files: true # so includes .next folder
      #     # path: website/.next/standalone
      #     path: downloadedArtifacts/asdf-${{ matrix.os }}.zip.sig

      - run: echo ${{ steps.upload-web-zip.outputs.artifact-url }}

      ## Write for matrix outputs workaround
      - uses: cloudposse/github-action-matrix-outputs-write@v1
        id: out
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.os }}
          outputs: |-
            web-zip-url: ${{ steps.upload-web-zip.outputs.artifact-url }}
            ## Multiline string
            ## web-zip-sig-url: ${{ steps.upload-web-zip.outputs.artifact-url }}
            web-zip-sig: ${{ steps.sign-files.outputs.value }}

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: asdf-${{ matrix.os }}.sig
      #     include-hidden-files: true # so includes .next folder
      #     # path: downloadedArtifacts/asdf-${{ matrix.os }}.sig
      #     path: asdf-${{ matrix.os }}.sig

      # At the end, set/create var in environment for the "1.2.3" of this build.
      # Probably in another job since this one is a matrix.

  read_workflow:
    needs: [build_website]
    runs-on: ubuntu-latest
    steps:
      ## Read matrix outputs
      - uses: cloudposse/github-action-matrix-outputs-read@v1
        id: read
        with:
          matrix-step-name: build_website
      - run: echo ${{ steps.read.outputs.result }}
    outputs:
      result: '${{ steps.read.outputs.result }}'

  # THIS one was before changing to trigger. Reusable was not what we were looking for.
  # runs_reusable_workflow:
  #   needs: [read_workflow]
  #   uses: icogn/tpr-gen3/.github/workflows/reusable.yml@main
  #   with:
  #     input_one: ${{ needs.read_workflow.outputs.result }}

  trigger_pull_artifact_workflow:
    needs: [read_workflow]
    runs-on: ubuntu-latest
    steps:
      - run: exit 1 # temp

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          cache: 'yarn'

      # - uses: qoomon/actions--context@v2
      #   name: Get environment name as var
      #   id: context

      - run: yarn --immutable

      - uses: ./scripts/workflows/trigger-pull-artifacts
        name: Trigger pull artifacts in central repo
        with:
          # https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event
          # Note that the fine-grained token needs `"Contents" repository permissions (write)`
          token: ${{ secrets.GH_PAT }}
          artifactInfo: ${{ needs.read_workflow.outputs.result }}
