name: Website Artifact
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_website:
    # permissions: write-all
    strategy:
      fail-fast: true
      matrix:
        # os: [windows-latest]
        os: [ubuntu-latest]
        # os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    environment: dev

    steps:
      - uses: actions/checkout@v4

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20.17.0'
      # - name: Setup yarn
      #   run: npm install -g yarn

      - uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          cache: 'yarn'

      - run: yarn --immutable

      - run: |
          gh variable list
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - run: echo ${{ vars.TESTREPOVAR }}

      # - uses: action-pack/increment@v2
      - uses: ./scripts/ci/increment.js
        id: increment
        with:
          name: 'TESTREPOVAR'
          token: ${{ secrets.GH_PAT }}

      # - uses: ./scripts/ci/set-github-variable.js
      #   with:
      #     name: 'SAMPLE_VAR'
      #     value: 'Hello World'
      #     repository: mmoyaferrer/set-github-variable
      #     token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - run: yarn --cwd website run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: asdf-${{ matrix.os }}
          include-hidden-files: true # so includes .next folder
          path: website/.next/standalone
