name: Test Target Workflow
on:
  workflow_dispatch:

jobs:
  do_stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          ref: 'config_branch'
          path: 'config_branch'

      - uses: ./scripts/workflows/pull-web-artifacts
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          clientPayloadFromFile: 'true'
