name: Test Target Workflow
on:
  workflow_dispatch:

jobs:
  do_stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check config branch exists
        id: check-branch-exists
        run: |
          if [[ -n $(git ls-remote --heads origin config_branchasdhfio) ]]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "config branch does not exist."
            echo "exists=false" >> $GITHUB_OUTPUT          
          fi
        shell: bash

      # - name: Stop if config branch doesn't exist
      #   if: ${{ steps.check-branch-exists.outputs.exists }} != 'true'
      #   run: exit 1

      - run: echo ${{ steps.check-branch-exists.outputs.exists }}

      - if: ${{ steps.check-branch-exists.outputs.exists }} == 'true'
        uses: actions/checkout@v4
        id: config-checkout
        with:
          ref: 'config_branch'
          path: 'config_branch'

      - if: ${{ steps.check-branch-exists.outputs.exists }} == 'true'
        uses: ./scripts/workflows/pull-web-artifacts
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          clientPayloadFromFile: 'true'
