name: 'Sign Files Action'
description: 'Create signature files with the given private key'
branding:
  icon: 'check-circle'
  color: 'gray-dark'
inputs:
  privateKey:
    description: 'The private key that will be used to sign the files'
    required: true
  passphrase:
    description: 'Private key passphrase'
    required: false
  file:
    description: 'File to sign'
    required: true
  algorithm:
    description: 'Algorithm used to sign the files'
    required: false
    default: 'RSA-SHA256'
  encoding:
    description: 'Encoding of signature'
    required: false
    default: 'base64'

outputs:
  value:
    description: Output value

runs:
  using: node20
  main: 'sign-files.js'
